language: node_js
node_js:
  - "0.12"
before_install:
  - npm install -g npm
  - npm install
script:
  - npm test
  - npm run-script test-travis
# Send coverage data to Coveralls
after_script: "cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js"